dist: bionic

git:
  depth: 3

language: python
python:
  - '3.6'

before_install:
  - curl -sSLO https://github.com/lcm-proj/lcm/releases/download/v1.3.1/lcm-1.3.1.zip
  - unzip lcm-1.3.1.zip
  - pushd lcm-1.3.1
  - PYTHON=`which python3.6` ./configure
  - make
  - sudo make install
  - popd

# Travis installs requirements from pip by default
#install:
#  - pip install -r requirements.txt

script:
  - pushd test/types && lcm-gen -p *.lcm && popd
  - python3 lcm_export/lcmlog_export.py --lcmtypes test/types test/data/lcmlog-test.00
  - pytest
